version: '3.0'
services:
  lisbom_database:
    image: postgres
    container_name: lisbom_database
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
    ports:
      - 5432:${PG_PORT}
